[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
bytes = "1.2.1"
chrono = "0.4.22"
tokio = { version = "1.21.1", features = ["full"] }
